name: CI/CD using github actions & docker

on:
  push:
    branches: [ "refactor" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: make Arbaguette application.yml
        run: |
          cd ./backend/Arbaguette/src/main/resources
          echo "${{ secrets.YML }}" > application.yml
        shell: bash

      - name: make Bonus application.yml
        run: |
          cd ./backend/bonus/src/main/resources
          echo "${{ secrets.YML_BONUS }}" > application.yml
        shell: bash

      - name: Build Arbaguette
        run: |
          chmod +x ./gradlew
          cd ./backend/Arbaguette
          ./gradlew build -x test

      - name: Build Bonus
        run: |
          chmod +x ./gradlew
          cd ./backend/bonus
          ./gradlew build -x test

      - name: Docker build & push Arbaguette
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f backend/Arbaguette/Dockerfile-dev -t ${{ secrets.DOCKER_USERNAME }}/docker-arba-prod backend/Arbaguette
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-arba-prod

      - name: Docker build & push Bonus
        run: |
          docker build -f backend/bonus/Dockerfile-dev -t ${{ secrets.DOCKER_USERNAME }}/docker-bonus-prod backend/bonus
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-bonus-prod

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            # Arbaguette
            sudo docker stop docker-arba-prod || true
            sudo docker rm docker-arba-prod || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/docker-arba-prod
            sudo docker run -d --name docker-arba-prod -p 8082:8082 ${{ secrets.DOCKER_USERNAME }}/docker-arba-prod

            # Bonus
            sudo docker stop docker-bonus-prod || true
            sudo docker rm docker-bonus-prod || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/docker-bonus-prod
            sudo docker run -d --name docker-bonus-prod -p 8083:8083 ${{ secrets.DOCKER_USERNAME }}/docker-bonus-prod

            sudo docker image prune -f
